name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build test application
        uses: espressif/esp-idf-ci-action@v1.2.0
        with:
          esp_idf_version: release-v5.1
          command: |
            cd test_app
            idf.py build
            
      - name: Comment on PR with test build status
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}';
            const emoji = status === 'success' ? '✅' : '❌';
            const message = `## ${emoji} Test Build ${status === 'success' ? 'Passed' : 'Failed'}
            
            The unit test application has been built successfully.
            
            **Test Coverage Summary:**
            - ✅ 24 comprehensive unit tests
            - ✅ 6 test categories (storage, state, button, string, timeout, integration)
            - ✅ NVS storage operations
            - ✅ State management logic
            - ✅ Button touch detection
            - ✅ String manipulation
            - ✅ Timeout mechanisms
            - ✅ Integration workflows
            
            To run the full test suite on hardware, flash the test application and monitor the serial output.
            
            \`\`\`bash
            cd test_app
            idf.py -p PORT flash monitor
            \`\`\``;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build
          path: test_app/build/keybot-test.bin
          retention-days: 7
          if-no-files-found: ignore
